spring.application.name=Scrapper
spring.datasource.url=jdbc:postgresql://localhost:5432/scrapped
spring.datasource.username=postgres
spring.datasource.password=password
spring.threads.virtual.enabled=true
urls:https://books.toscrape.com/
